"""Initial migration.

Revision ID: 09bed2ab7221
Revises: 
Create Date: 2024-02-06 01:32:10.824801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bed2ab7221'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=162), nullable=False),
    sa.Column('ios_token', sa.String(length=256), nullable=True),
    sa.Column('android_token', sa.String(length=256), nullable=True),
    sa.Column('web_token', sa.String(length=256), nullable=True),
    sa.Column('windows_token', sa.String(length=256), nullable=True),
    sa.Column('mac_token', sa.String(length=256), nullable=True),
    sa.Column('linux_token', sa.String(length=256), nullable=True),
    sa.Column('browser_token', sa.String(length=256), nullable=True),
    sa.Column('email_notification_token', sa.String(length=256), nullable=True),
    sa.Column('notification_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('search_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_histories')
    op.drop_table('users')
    # ### end Alembic commands ###
