"""Added stripe token storage

Revision ID: 4671342e2b60
Revises: 09bed2ab7221
Create Date: 2024-04-24 00:46:48.658140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4671342e2b60'
down_revision = '09bed2ab7221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripetoken', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stripetoken')

    # ### end Alembic commands ###
